# Softmax Regression

In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
df = pd.read_excel("Dry_Bean_Dataset.xlsx")
df = df.drop_duplicates()
X = df.iloc[:,:16]
y = df.iloc[:,16:]
y = y.reset_index().drop(columns = "index")
scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns = X.columns)
pt = PowerTransformer(method = "yeo-johnson")
X = pd.DataFrame(pt.fit_transform(X), columns = X.columns)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 101)

In [5]:
Logit = LogisticRegressionCV(cv=10, scoring='accuracy', n_jobs=-1, multi_class = "multinomial", max_iter = 100, solver = "newton-cg")
Logit.fit(X_train, np.ravel(y_train))
y_pred = Logit.predict(X_test)

In [6]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=y.Class.unique()))

[[244   1   9   0   0   1   5]
 [  0 115   0   0   0   0   0]
 [ 14   0 319   0   0   2   4]
 [  0   0   0 662   0   7  44]
 [  0   0   6   3 333   0   6]
 [  2   0   0   9   0 387  11]
 [  0   0   4  47  11   6 457]]
              precision    recall  f1-score   support

       SEKER       0.94      0.94      0.94       260
    BARBUNYA       0.99      1.00      1.00       115
      BOMBAY       0.94      0.94      0.94       339
        CALI       0.92      0.93      0.92       713
       HOROZ       0.97      0.96      0.96       348
        SIRA       0.96      0.95      0.95       409
    DERMASON       0.87      0.87      0.87       525

    accuracy                           0.93      2709
   macro avg       0.94      0.94      0.94      2709
weighted avg       0.93      0.93      0.93      2709



In [8]:
metrics.accuracy_score(y_test, y_pred)

0.929125138427464